require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Metrics:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
